-- Fact table. Loaders replace this table from pandas; script kept for documentation.

CREATE TABLE IF NOT EXISTS fact_purchase_orders (
    po_id TEXT,
    po_line_id TEXT PRIMARY KEY,
    supplier_id TEXT,
    supplier_name TEXT,
    material_id TEXT,
    material_description TEXT,
    category TEXT,
    region TEXT,
    plant TEXT,
    plant_name TEXT,
    order_date TEXT,
    po_creation_date TEXT,
    po_approval_date TEXT,
    requested_delivery_date TEXT,
    promised_delivery_date TEXT,
    actual_delivery_date TEXT,
    ordered_quantity REAL,
    received_quantity REAL,
    defective_quantity REAL,
    unit_price REAL,
    standard_price REAL,
    currency TEXT,
    payment_terms TEXT,
    lead_time_days INTEGER,
    actual_lead_time_days INTEGER,
    sla_days INTEGER,
    carrier TEXT,
    carrier_id TEXT,
    delivery_status TEXT,
    quality_status TEXT,
    delivery_days_late INTEGER,
    delivery_days_early INTEGER,
    quantity_shortfall REAL,
    defect_rate REAL,
    cost_variance REAL,
    cost_variance_pct REAL,
    otif_flag INTEGER,
    fill_rate REAL,
    sla_breach_flag INTEGER,
    late_only_flag INTEGER,
    qty_short_only_flag INTEGER,
    late_and_short_flag INTEGER,
    po_turnaround_days INTEGER,
    actual_spend REAL,
    expected_spend REAL,
    ordered_spend REAL,
    year_month TEXT
);
